server:
  port: 9898

spring:
  application:
    name: pet-health-portal

  liquibase:
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}

  datasource:
    url: jdbc:postgresql://localhost:9999/core
    username: core
    password: core

  jpa:
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public #TODO: Change later